SELECT MIN(COUNT_ID) min_categories, MAX(COUNT_ID) max_categories,
       AVG(COUNT_ID) mean_categories, MEDIAN(COUNT_ID) median_categories  FROM
(SELECT COUNT(CATEGORY_ID) COUNT_ID FROM BUSINESS_HAS_CATEGORIES GROUP BY BUSINESS_ID)