
-- E_1
SELECT B.BUSINESS_NAME, B.REVIEW_COUNT
FROM BUSINESS B, BUSINESS_LOCATION BL, BUSINESS_PARKING_TYPE BPT, BUSINESS_HOURS BH
WHERE B.BUSINESS_ID = BL.BUSINESS_ID AND BL.CITY_NAME = 'las vegas'
AND B.BUSINESS_ID = BPT.BUSINESS_ID AND BPT.PARKING_TYPE_ID = 0
AND B.BUSINESS_ID = BH.BUSINESS_ID AND BH.DAY_ID = 4
AND B.STARS = 5
ORDER BY B.BUSINESS_NAME;

-- E_2
SELECT B.BUSINESS_NAME, B.STARS
FROM BUSINESS B, BUSINESS_LOCATION BL
WHERE B.BUSINESS_ID = BL.BUSINESS_ID AND BL.STATE_NAME = 'CA'
ORDER BY B.STARS DESC, B.BUSINESS_NAME
FETCH FIRST 10 ROWS ONLY;

-- E_3
SELECT R.BUSINESS_ID
FROM REVIEWS R
GROUP BY R.BUSINESS_ID
HAVING COUNT(DISTINCT USER_ID) > 1030
ORDER BY COUNT(DISTINCT USER_ID);

-- E_4
SELECT B.BUSINESS_ID, B.BUSINESS_NAME, B.REVIEW_COUNT
FROM BUSINESS B,
     (SELECT BDR.BUSINESS_ID
      FROM BUSINESS_DIETARY_RESTRICTIONS BDR
      GROUP BY BDR.BUSINESS_ID
      HAVING COUNT(BDR.DIETARY_REST_ID) > 2) BDR2
WHERE B.BUSINESS_ID = BDR2.BUSINESS_ID AND B.REVIEW_COUNT > 3000;

-- E_5
SELECT UY.USER_ID, UY.USER_NAME, UY.YELPING_SINCE
FROM USER_YELP UY
WHERE UY.YELPING_SINCE < '01-JAN-2007' AND
      LENGTH(UY.USER_NAME) = 1
ORDER BY UY.USER_NAME
FETCH FIRST 50 ROWS ONLY;

-- E_6
SELECT MAX(numReviews) AS count
FROM (
    SELECT R.USER_ID, COUNT(DISTINCT R.BUSINESS_ID) AS numReviews
    FROM REVIEWS R
    GROUP BY R.USER_ID
);



