SELECT CITY_NAME FROM CITIES WHERE (STATE_NAME, CITY_NAME) NOT IN
        (SELECT STATE_NAME, CITY_NAME FROM BUSINESS_LOCATION INNER JOIN
        (SELECT BUSINESS_ID FROM BUSINESS_HOURS GROUP BY BUSINESS_ID HAVING COUNT(DISTINCT DAY_ID) > 5)
         IDS ON IDS.BUSINESS_ID = BUSINESS_LOCATION.BUSINESS_ID) ORDER BY CITY_NAME;