SELECT B.BUSINESS_NAME, B.STARS, B.REVIEW_COUNT
FROM BUSINESS B
WHERE B.BUSINESS_ID IN (
    SELECT BHC.BUSINESS_ID
    FROM BUSINESS_HAS_CATEGORIES BHC
    WHERE BHC.CATEGORY_ID = (
        SELECT BC.CATEGORY_ID
        FROM BUSINESS_CATEGORIES BC
        WHERE BC.CATEGORY_NAME = 'Irish Pub'
        )
    )
    AND B.BUSINESS_ID IN (
        SELECT BM.BUSINESS_ID
        FROM BUSINESS_MUSIC BM
        WHERE BM.MUSIC_ID = (
            SELECT M.MUSIC_ID
            FROM MUSIC M
            WHERE M.MUSIC_DESCRIPTION = 'live'
            )
    )
ORDER BY B.BUSINESS_NAME;

