SELECT CITY_NAME
FROM (
    SELECT BL.CITY_NAME
    FROM BUSINESS_LOCATION BL
    JOIN BUSINESS B ON BL.BUSINESS_ID = B.BUSINESS_ID
    GROUP BY BL.CITY_NAME
    HAVING MIN(B.REVIEW_COUNT) >= 2
)
ORDER BY CITY_NAME
FETCH FIRST 50 ROWS ONLY;

