-- Inefficient Query
SELECT AVG(B.STARS), SUM(B.REVIEW_COUNT)
FROM BUSINESS B
WHERE (
    SELECT COUNT(*)
    FROM BUSINESS_HAS_CATEGORIES BHC
    WHERE B.BUSINESS_ID = BHC.BUSINESS_ID
) >= 2
AND (
    SELECT COUNT(*)
    FROM Business_parking_type BPT
    WHERE B.BUSINESS_ID = BPT.BUSINESS_ID
) > 1;

-- Optimized Query
WITH QUERY_BLOCK1 AS (
  SELECT BUSINESS_ID
  FROM BUSINESS_HAS_CATEGORIES
  GROUP BY BUSINESS_ID
  HAVING COUNT(CATEGORY_ID) >= 2
),
QUERY_BLOCK2 AS (
  SELECT BUSINESS_ID
  FROM BUSINESS_PARKING_TYPE
  GROUP BY BUSINESS_ID
  HAVING COUNT(PARKING_TYPE_ID) > 1
),
COMBINED AS (
  SELECT QUERY_BLOCK1.BUSINESS_ID
  FROM QUERY_BLOCK1
  INNER JOIN QUERY_BLOCK2 ON QUERY_BLOCK1.BUSINESS_ID = QUERY_BLOCK2.BUSINESS_ID
)
SELECT AVG(stars), SUM(review_count)
FROM BUSINESS
WHERE BUSINESS_ID IN (SELECT BUSINESS_ID FROM COMBINED);
