SELECT AVG(STARS) AS stars, SUM(REVIEW_COUNT) AS review_count
FROM BUSINESS
WHERE BUSINESS_ID IN (
    SELECT BHC.BUSINESS_ID
    FROM BUSINESS_HAS_CATEGORIES BHC
    GROUP BY BHC.BUSINESS_ID
    HAVING COUNT(CATEGORY_ID) >= 2
)
AND BUSINESS_ID IN (
    SELECT BPT.BUSINESS_ID
    FROM BUSINESS_PARKING_TYPE BPT
    GROUP BY BPT.BUSINESS_ID
    HAVING COUNT(PARKING_TYPE_ID) > 1
);
