SELECT DIVEY_AVG_STARS - UPSCALE_AVG_STARS AS DIFFERENCE_OF_AVERAGES FROM
(SELECT AVG(STARS) AS DIVEY_AVG_STARS FROM BUSINESS WHERE BUSINESS_ID IN
(SELECT * FROM (SELECT BUSINESS_ID FROM BUSINESS_GOOD_FOR_MEAL WHERE GOOD_FOR_MEAL_ID =
(SELECT GOOD_FOR_MEAL_ID FROM GOOD_FOR_MEAL WHERE GOOD_FOR_MEAL_DESCRIPTION = 'dinner')) GOODFORDINNER
WHERE GOODFORDINNER.BUSINESS_ID IN
(SELECT BUSINESS_ID FROM BUSINESS_AMBIANCE WHERE AMBIANCE_ID = (SELECT AMBIANCE_ID FROM AMBIANCE WHERE AMBIANCE_DESCRIPTION = 'divey')))),
(SELECT AVG(STARS) AS UPSCALE_AVG_STARS FROM BUSINESS WHERE BUSINESS_ID IN
(SELECT * FROM (SELECT BUSINESS_ID FROM BUSINESS_GOOD_FOR_MEAL WHERE GOOD_FOR_MEAL_ID =
(SELECT GOOD_FOR_MEAL_ID FROM GOOD_FOR_MEAL WHERE GOOD_FOR_MEAL_DESCRIPTION = 'dinner')) GOODFORDINNER
WHERE GOODFORDINNER.BUSINESS_ID IN
(SELECT BUSINESS_ID FROM BUSINESS_AMBIANCE WHERE AMBIANCE_ID = (SELECT AMBIANCE_ID FROM AMBIANCE WHERE AMBIANCE_DESCRIPTION = 'upscale'))));