SELECT * FROM (
    SELECT R.Business_Id, ROW_NUMBER() OVER (PARTITION BY R.Business_Id ORDER BY REVIEW_COUNT DESC) as REVIEWER_RANK, UC.REVIEW_COUNT FROM (
        ((SELECT Business_Id FROM Business ORDER BY Review_Count DESC FETCH FIRST 10 ROWS ONLY) B
            INNER JOIN REVIEWS R ON B.Business_Id = R.Business_Id)
        INNER JOIN
            (SELECT USER_ID, COUNT(*) AS REVIEW_COUNT FROM Reviews GROUP BY USER_ID ORDER BY COUNT(*) DESC) UC
        ON R.User_Id = UC.User_Id))
WHERE REVIEWER_RANK < 4 ORDER BY Business_Id, REVIEW_COUNT DESC;
