SELECT DISTINCT B.BUSINESS_NAME, B.STARS
FROM BUSINESS B
WHERE B.BUSINESS_ID IN (SELECT BL.BUSINESS_ID
                        FROM BUSINESS_LOCATION BL
                        WHERE BL.STATE_NAME = 'CA')
ORDER BY B.STARS DESC, B.BUSINESS_NAME
FETCH FIRST 10 ROWS ONLY;




