SELECT DISTINCT BUSINESS_NAME, STARS
FROM BUSINESS
WHERE BUSINESS_ID IN (SELECT BUSINESS_ID
                        FROM BUSINESS_LOCATION
                        WHERE STATE_NAME = 'CA')
ORDER BY STARS DESC, BUSINESS_NAME
FETCH FIRST 10 ROWS ONLY;




