SELECT * FROM (SELECT DISTINCT STATE_NAME FROM CITIES) STATES;
SELECT * FROM BUSINESS_LOCATION L,
(SELECT * FROM BUSINESS_DIETARY_RESTRICTIONS B
WHERE B.DIETARY_REST_ID =
(SELECT DIETARY_REST_ID FROM DIETARY_RESTRICTIONS 
WHERE DIETARY_REST_DESCRIPTION = 'vegetarian')) VEG
WHERE L.BUSINESS_ID = VEG.BUSINESS_ID;